inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    # binstubs, and other utilities
    - bin/**/*
    - vendor/**/*
    - vendor/**/.*

Layout/EndOfLine:
  EnforcedStyle: lf
